// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxsM9Gzg-jIz-5GnL2B6uLN0v6xkBdlTQ',
    appId: '1:1090040053163:web:b70b456e69c23bce7966ee',
    messagingSenderId: '1090040053163',
    projectId: 'ironbook-gm-prod',
    authDomain: 'ironbook-gm-prod.firebaseapp.com',
    storageBucket: 'ironbook-gm-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjK-WgcK87jL87o-0qiPi6vVA7_Xv5Ykk',
    appId: '1:1090040053163:android:bfb1edbad41b48e87966ee',
    messagingSenderId: '1090040053163',
    projectId: 'ironbook-gm-prod',
    storageBucket: 'ironbook-gm-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNFfLU39k4ZME3fbSSBhW4GYb36CeSbs',
    appId: '1:1090040053163:ios:fb31b821b418e0a27966ee',
    messagingSenderId: '1090040053163',
    projectId: 'ironbook-gm-prod',
    storageBucket: 'ironbook-gm-prod.firebasestorage.app',
    iosBundleId: 'com.ironm.ironcontrol',
  );
}
